[flask]
debug = false

[presstagram]
background_image_path = "backgrounds/frc-24.png"
posts_dir = "posts/"
headers_path = "headers.json"
hashtag = "frcturkey"
number_of_posts = 50
image_quality = 80
image_base_width = 800
image_paste_coordinates = [133, 570]
